config/routes.rb
Rails.application.routes.draw do
  get 'student/home'
  get 'student/about'
  get 'student/management'
  get 'student/academics'
  get 'student/admissions'
  get 'student/departments'
  get 'student/facilities'
  get 'student/placements'
  get 'student/gallery'
  get 'student/contact'
  get 'student/vision'
  get 'student/mission'
  get 'student/qualitypolicy'
  get 'student/society'
  get 'student/campusvisit'
  get 'student/strengths'
  get 'student/academicregulations'
  get 'student/academiccalender'
  get 'student/incentives'
  get 'student/socialservices'
  get 'student/admissionprocedure'
  get 'student/coursesoffered'
  get 'student/feestructure'
  get 'student/cse'
  get 'student/eee'
  get 'student/ece'
  get 'student/mec'
  get 'student/civ'
  get 'student/min'
  get 'student/mba'
  get 'student/mtec'
  get 'student/library'
  get 'student/digitallibrary'
  get 'student/internet'
  get 'student/englishlab'
  get 'student/counselling'
  get 'student/seminarhall'
  get 'student/sports'
  get 'student/girlshostel'
  get 'student/boyshostel'
  get 'student/transportation'
  get 'student/canteen'
  get 'student/eclassroom'
  get 'student/templeincollege'
  get 'student/placementrecords'
  get 'student/crtprograms'
  get 'student/companies'
  get 'student/noticeboard'
 root 'student#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  def home
  end

  def about
  end
  def management
  end
  def academics
  end
  def gallery
  end
  def admissions
  end
  def departments
  end
  def facilities
  end
  def placements
  end
  def contact
  end
  def vision
  end
  def mission
  end
  def qualitypolicy
  end
  def society
  end
  def campusvisit
  end
  def strengths
  end
  def academicregulations
  end
  def academiccalender
  end
  def incentives
  end
  def socialservices
  end
  def admissionprocedure
  end
  def coursesoffered
  end
  def feestructure
  end
  def cse
  end
  def eee
  end
  def ece
  end
  def mec
  end
  def civ
  end
  def min
  end
  def mba
  end
  def mtech
  end
  def library
  end
  def digitallibrary
  end
  def internet
  end
  def englishlab
  end
  def counselling
  end
  def seminarhall
  end
  def sports
  end
  def girlshostel
  end
  def boyshostel
  end
  def transportation
  end
  def canteen
  end
  def eclassroom
  end
  def templeincollege
  end
  def placementrecords
  end
  def crtprograms
  end
  def companies
  end
  def noticeboard
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>College</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/student/about.html.erb
<h1>Student#about</h1>
<p>Find me in app/views/student/about.html.erb</p>

app/views/student/academiccalender.html.erb
<html>
<head>
<table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color:#ff0000"
      <tbody><tr>
        <td rowspan="2" width="156" align="center" valign="middle"><a href="index.html"><img src="assets/akitsl.jpg" width="170" height="161"></a></td>
        <td class="nav" width="1109" align="right"><a href="index.html" class="nav">Home</a> | <a href="contact-us.html" class="nav">Contact us</a> | <a href="sitemap.html" class="nav">Sitemap</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
      </tr>
      <tr>
        <td style="line-height:1.7em" align="left" valign="middle"><div align="center"><span class="style2">ABDUL KALAM INSTITUTE OF TECHNOLOGICAL SCIENCES</span><br>
            <span class="style6">( Approved by AICTE, New Delhi &amp; Affiliated to JNTUH, Hyderabad, ISO 9001:2008 certified Institution )</span><em><br>
            </em><span class="style4"> EAMCET / ECET / ICET / DIPLOMA COUNSELING CODE : <strong><span class="style7">AKIT</span><br>
            Contact @ 9133397889 , 9866698961, 9133397888  </strong></span><span class="style9">, </span><span class="style8">E-mail@ akits.org@gmail.com </span><br> 
            <br>
            </div></td>
      </tr>
    </tbody></table>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <ul class="nav" role="navigation">
  <li class="explore">
    <%= link_to 'HOME ',  student_home_path, :id => 'setupdrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
      
     
      <li class="dropdown-link"><%= link_to "MANAGEMENT",{:controller=>"student",:action=>"management"}%></a></a></li>
      <li class="dropdown-link"><a href="#">Recently Added</a></a></li>
      <li class="dropdown-link"><a href="#">Most Liked</a></a></li>
    </ul>
    <div class="dropdown-divider"></div>
        </div>
  </li>
</ul>
 <ul class="nav" role="navigation">
  <li class="explore">
    <%= link_to 'ABOUT ',  student_about_path, :id => 'setupdrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
      <li class="nav-header">Managment</li>
     
      <li class="dropdown-link"><%= link_to "MANAGEMENT",{:controller=>"student",:action=>"management"}%></a></a></li>
      <li class="dropdown-link"><a href="#">Recently Added</a></a></li>
      <li class="dropdown-link"><a href="#">Most Liked</a></a></li>
    </ul>
    <div class="dropdown-divider"></div>
        </div>
  </li>

        </ul>
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ACADEMICS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"<%=link_to"ACADEMIC REGULATIONS",student_academicregulations_path%></a>
          <a class="dropdown-item"<%=link_to"ACADEMIC CALENDER",student_academiccalender_path%> </a>
          <a class="dropdown-item"<%=link_to"INCENTIVES",student_incentives_path%></a>
          <a class="dropdown-item" <%=link_to"SOCIAL SERVICES",student_socialservices_path%></a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ADMISSIONS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to"ADMISSION PROSEDURE",student_admissionprocedure_path%></a>
          <a class="dropdown-item" <%=link_to"COURSES OFFERED",student_coursesoffered_path%></a>
          <a class="dropdown-item" <%=link_to"FEE STRUCTURE",student_feestructure_path%></a>
          
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        DEPARTMENTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to "CSE",student_about_path %></a>
          <a class="dropdown-item" href="#">EEE</a>
          <a class="dropdown-item" href="#">MECHANICAL</a>
          <a class="dropdown-item" href="#">CIVIL</a>
           <a class="dropdown-item" href="#">MINING</a>
            <a class="dropdown-item" href="#">ECE</a>
             <a class="dropdown-item" href="#">MBA</a>
              <a class="dropdown-item" href="#">M.TECH</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        FACILITIES
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to"LIBRARY",student_library_path%></a>
          <a class="dropdown-item" <%=link_to"DIGITAL LIBRARY",student_digitallibrary_path%></a>
          <a class="dropdown-item" <%=link_to"INTERNET",student_internet_path%></a>
          <a class="dropdown-item" <%=link_to"ENGLISH LAB",student_englishlab_path%></a>
           <a class="dropdown-item" <%=link_to"COUNSELLING",student_counselling_path%></a>
            <a class="dropdown-item" <%=link_to"SEMINAR HALL",student_seminarhall_path%></a>
             <a class="dropdown-item" <%=link_to"SPORTS",student_sports_path%></a>
              <a class="dropdown-item" <%=link_to"GIRLS HOSTEL",student_girlshostel_path%></a>
               <a class="dropdown-item" <%=link_to"BOYS HOSTEL",student_boyshostel_path%></a>
          <a class="dropdown-item" <%=link_to"TRANSPORTATION",student_transportation_path%></a>
          <a class="dropdown-item" <%=link_to"CANTEEN",student_canteen_path%></a>
           <a class="dropdown-item" <%=link_to"E-CLASS ROOM",student_eclassroom_path%></a>
            <a class="dropdown-item" <%=link_to"TEMPLE IN COLLEGE",student_templeincollege_path%></a>
             
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        PLACEMENTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to"PLACEMENT RECORDS",student_placementrecords_path%></a>
          <a class="dropdown-item" <%=link_to"CRT PROGRAMS",student_crtprograms_path%></a>
          <a class="dropdown-item" <%=link_to"COMPANIES",student_companies_path%></a>
           <a class="dropdown-item" <%=link_to"NOTICE BOARD",student_noticeboard_path%></a>
        <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%=link_to"GALLERY",student_gallery_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CONTACT </a>
      </li>

        
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <img class="d-block w-100" src="assets/akits1.jpg">
    </div>
    <!--/First slide-->
    <!--Second slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/akits2.jpg">
    </div>
    <!--/Second slide-->
    <!--Third slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/akits4.jpg">
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<div>
<p> W e l c o m e !, Abdul kalam Institute of Technological Sciences (AKITS) has blossomed out as one of the well-equipped Engineering College at the starting stage itself. The laudable aim of this institution is to provide qualitative and fruitful engineering education to the students by offering modernised teaching and training, by undertaking valuable research programmes and by exchanging consultancy activities with outstanding organisations. It is also the noble objective of this institution to make the students realise and adopt in their life, the significance of discipline and the invaluable price of human virtues.

In an attempt to implement the concept of our mission, we have chosen to establish an engineering college in Rural areas of Bhadradri-Kothagudem District. The college is centrally located in this district in Bhadradri-Kothagudem, reachable to all corners of the District and neighbouring Districts. We are planning to convert the college into a “Center for Excellence” by 2020. We aim at quality rather than quantity.
   Courses & Intake
        B.Tech ( EEE- 120, ECE- 60, CSE- 60, Mechanical- 60, Civil- 60, Mining- 60 )
        MBA - 120
        Polytechnic/Diploma ( EEE- 60, Mechanical- 60, Mining- 60 ) 
        </p>
        </div>
<!--/.Carousel Wrapper--></body>
</head>
</html>

app/views/student/canteen.html.erb
<html>
<head>
<table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color:#ff0000"
      <tbody><tr>
        <td rowspan="2" width="156" align="center" valign="middle"><a href="index.html"><img src="assets/akitsl.jpg" width="170" height="161"></a></td>
        <td class="nav" width="1109" align="right"><a href="index.html" class="nav">Home</a> | <a href="contact-us.html" class="nav">Contact us</a> | <a href="sitemap.html" class="nav">Sitemap</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
      </tr>
      <tr>
        <td style="line-height:1.7em" align="left" valign="middle"><div align="center"><span class="style2">ABDUL KALAM INSTITUTE OF TECHNOLOGICAL SCIENCES</span><br>
            <span class="style6">( Approved by AICTE, New Delhi &amp; Affiliated to JNTUH, Hyderabad, ISO 9001:2008 certified Institution )</span><em><br>
            </em><span class="style4"> EAMCET / ECET / ICET / DIPLOMA COUNSELING CODE : <strong><span class="style7">AKIT</span><br>
            Contact @ 9133397889 , 9866698961, 9133397888  </strong></span><span class="style9">, </span><span class="style8">E-mail@ akits.org@gmail.com </span><br> 
            <br>
            </div></td>
      </tr>
    </tbody></table>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <ul class="nav" role="navigation">
  <li class="explore">
    <%= link_to 'HOME ',  student_home_path, :id => 'setupdrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
      
     
      <li class="dropdown-link"><%= link_to "MANAGEMENT",{:controller=>"student",:action=>"management"}%></a></a></li>
      <li class="dropdown-link"><a href="#">Recently Added</a></a></li>
      <li class="dropdown-link"><a href="#">Most Liked</a></a></li>
    </ul>
    <div class="dropdown-divider"></div>
        </div>
  </li>
</ul>
 <ul class="nav" role="navigation">
  <li class="explore">
    <%= link_to 'ABOUT ',  student_about_path, :id => 'setupdrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
      <li class="nav-header">Managment</li>
     
      <li class="dropdown-link"><%= link_to "MANAGEMENT",{:controller=>"student",:action=>"management"}%></a></a></li>
      <li class="dropdown-link"><a href="#">Recently Added</a></a></li>
      <li class="dropdown-link"><a href="#">Most Liked</a></a></li>
    </ul>
    <div class="dropdown-divider"></div>
        </div>
  </li>

        </ul>
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ACADEMICS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"<%=link_to"ACADEMIC REGULATIONS",student_academicregulations_path%></a>
          <a class="dropdown-item"<%=link_to"ACADEMIC CALENDER",student_academiccalender_path%> </a>
          <a class="dropdown-item"<%=link_to"INCENTIVES",student_incentives_path%></a>
          <a class="dropdown-item" <%=link_to"SOCIAL SERVICES",student_socialservices_path%></a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ADMISSIONS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to"ADMISSION PROSEDURE",student_admissionprocedure_path%></a>
          <a class="dropdown-item" <%=link_to"COURSES OFFERED",student_coursesoffered_path%></a>
          <a class="dropdown-item" <%=link_to"FEE STRUCTURE",student_feestructure_path%></a>
          
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        DEPARTMENTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to "CSE",student_about_path %></a>
          <a class="dropdown-item" href="#">EEE</a>
          <a class="dropdown-item" href="#">MECHANICAL</a>
          <a class="dropdown-item" href="#">CIVIL</a>
           <a class="dropdown-item" href="#">MINING</a>
            <a class="dropdown-item" href="#">ECE</a>
             <a class="dropdown-item" href="#">MBA</a>
              <a class="dropdown-item" href="#">M.TECH</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        FACILITIES
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to"LIBRARY",student_library_path%></a>
          <a class="dropdown-item" <%=link_to"DIGITAL LIBRARY",student_digitallibrary_path%></a>
          <a class="dropdown-item" <%=link_to"INTERNET",student_internet_path%></a>
          <a class="dropdown-item" <%=link_to"ENGLISH LAB",student_englishlab_path%></a>
           <a class="dropdown-item" <%=link_to"COUNSELLING",student_counselling_path%></a>
            <a class="dropdown-item" <%=link_to"SEMINAR HALL",student_seminarhall_path%></a>
             <a class="dropdown-item" <%=link_to"SPORTS",student_sports_path%></a>
              <a class="dropdown-item" <%=link_to"GIRLS HOSTEL",student_girlshostel_path%></a>
               <a class="dropdown-item" <%=link_to"BOYS HOSTEL",student_boyshostel_path%></a>
          <a class="dropdown-item" <%=link_to"TRANSPORTATION",student_transportation_path%></a>
          <a class="dropdown-item" <%=link_to"CANTEEN",student_canteen_path%></a>
           <a class="dropdown-item" <%=link_to"E-CLASS ROOM",student_eclassroom_path%></a>
            <a class="dropdown-item" <%=link_to"TEMPLE IN COLLEGE",student_templeincollege_path%></a>
             
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        PLACEMENTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%=link_to"PLACEMENT RECORDS",student_placementrecords_path%></a>
          <a class="dropdown-item" <%=link_to"CRT PROGRAMS",student_crtprograms_path%></a>
          <a class="dropdown-item" <%=link_to"COMPANIES",student_companies_path%></a>
           <a class="dropdown-item" <%=link_to"NOTICE BOARD",student_noticeboard_path%></a>
        <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%=link_to"GALLERY",student_gallery_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CONTACT </a>
      </li>

        
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <img class="d-block w-100" src="assets/akits1.jpg">
    </div>
    <!--/First slide-->
    <!--Second slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/akits2.jpg">
    </div>
    <!--/Second slide-->
    <!--Third slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/akits4.jpg">
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<div>
<p> W e l c o m e !, Abdul kalam Institute of Technological Sciences (AKITS) has blossomed out as one of the well-equipped Engineering College at the starting stage itself. The laudable aim of this institution is to provide qualitative and fruitful engineering education to the students by offering modernised teaching and training, by undertaking valuable research programmes and by exchanging consultancy activities with outstanding organisations. It is also the noble objective of this institution to make the students realise and adopt in their life, the significance of discipline and the invaluable price of human virtues.

In an attempt to implement the concept of our mission, we have chosen to establish an engineering college in Rural areas of Bhadradri-Kothagudem District. The college is centrally located in this district in Bhadradri-Kothagudem, reachable to all corners of the District and neighbouring Districts. We are planning to convert the college into a “Center for Excellence” by 2020. We aim at quality rather than quantity.
   Courses & Intake
        B.Tech ( EEE- 120, ECE- 60, CSE- 60, Mechanical- 60, Civil- 60, Mining- 60 )
        MBA - 120
        Polytechnic/Diploma ( EEE- 60, Mechanical- 60, Mining- 60 ) 
        </p>
        </div>
<!--/.Carousel Wrapper--></body>
</head>
</html>